import type { StocksDictionary } from "./types";

export const enUS: StocksDictionary = {
  meta: {
    title: "Kaiju Stocks — B3 stock quotes",
    description: "Browse Brazilian (B3) stocks: top gainers and losers, volume by sector and price history.",
  },
  layout: {
    skipToContent: "Skip to content",
    backToPortfolio: "Back to portfolio",
    backShort: "Portfolio",
    footer: "Quotes delayed by up to 15 minutes. Not investment advice.",
    dataSource: "Data: brapi.dev",
  },
  nav: { label: "Kaiju Stocks navigation", market: "Market", portfolio: "Portfolio" },
  market: {
    title: "Market",
    subtitle: "Overview of the {n} most traded stocks and a searchable list of every listed ticker.",
    freeTickers: "History available without a token for:",
    summaryLabel: "Summary",
    up: "Up",
    down: "Down",
    ofMostTraded: "of the {n} most traded",
    averageChange: "Average change",
    averageChangeHint: "simple average of the day",
    totalVolume: "Total volume",
    totalVolumeHint: "shares traded",
    moversTitle: "Top gainers and losers",
    moversDescription: "Daily change among the most traded stocks",
    sectorsTitle: "Volume by sector",
    sectorsDescription: "Share of volume among the most traded stocks",
    others: "Others",
    allStocks: "All stocks",
    allStocksHint: "Click a stock to see its price history.",
  },
  filters: {
    searchPlaceholder: "Search ticker or company",
    searchLabel: "Search stocks",
    sectorLabel: "Filter by sector",
    allSectors: "All sectors",
  },
  table: {
    asset: "Stock",
    price: "Price",
    day: "Day",
    volume: "Volume",
    marketCap: "Market cap",
    sector: "Sector",
    empty: "No stocks match this filter.",
    pagination: "{total} stocks · page {page} of {pages}",
    paginationLabel: "Pagination",
    previous: "Previous",
    next: "Next",
  },
  detail: {
    back: "Back to market",
    updatedAt: "Updated {date}",
    indicators: "Indicators",
    open: "Open",
    previousClose: "Prev. close",
    dayRange: "Day low / high",
    yearRange: "52-week low / high",
    volume: "Volume",
    marketCap: "Market cap",
    pe: "P/E",
    eps: "EPS",
    quote: "Price",
    periodChange: "In period",
    min: "low",
    max: "high",
    rangeLabel: "Period",
    proRanges: "1Y and 5Y require brapi's Pro plan",
    tradedVolume: "Traded volume",
    noHistory: "No history for this period.",
    history: "History",
    lastSessions: "Last {n} trading sessions in the period",
    date: "Date",
    low: "Low",
    high: "High",
    close: "Close",
    needsToken: "{ticker} history requires a token",
    needsTokenDescription: "Without a token, brapi only serves details for {tickers}. Create a free token at brapi.dev and set BRAPI_TOKEN in the environment.",
    unavailable: "Couldn't load the quote",
    tryAgain: "Please try again in a moment.",
    ranges: { "5d": "5D", "1mo": "1M", "3mo": "3M", "1y": "1Y", "5y": "5Y" },
  },
  charts: { change: "Change", close: "Close", volume: "Volume" },
  crypto: {
    title: "Crypto",
    description: "The largest coins by market cap, priced in reais, with their 24-hour change.",
    moversTitle: "Top gainers and losers (24h)",
    moversDescription: "Among the {n} largest by market cap",
    topTitle: "Largest by market cap",
    topDescription: "Price in reais and 24-hour change",
    rank: "#",
    asset: "Coin",
    price: "Price",
    change: "24h",
    marketCap: "Market cap",
    source: "Crypto data: CoinGecko",
    track: "Track it in your portfolio",
  },
  states: {
    notFound: "Stock not found.",
    backToMarket: "Back to market",
    errorTitle: "Couldn't load the market",
    errorDescription: "brapi didn't respond. Please try again in a moment.",
    retry: "Try again",
  },
  portfolio: {
    meta: {
      title: "Portfolio",
      description: "Track stocks, REITs, ETFs and crypto with average price, returns, dividends and a CDI benchmark — data saved only in your browser.",
    },
    title: "My portfolio",
    subtitle: "Average price, returns, dividends and a CDI benchmark for your B3 stocks, REITs (FIIs), ETFs and crypto.",
    privacy: "Your data stays in this browser only — nothing is sent to any server.",
    actions: {
      add: "Add transaction",
      import: "Import from B3",
      backup: "Backup",
      export: "Export backup (JSON)",
      restore: "Restore backup",
      clear: "Delete portfolio",
      clearTitle: "Delete the portfolio?",
      clearDescription: "Every transaction saved in this browser will be removed. Export a backup first if you want to keep it.",
      confirmClear: "Delete everything",
      cancel: "Cancel",
    },
    empty: {
      title: "Your portfolio is empty",
      description: "Add your transactions by hand, import the spreadsheet from B3's Investor Area or try it out with a sample portfolio.",
      demo: "See a sample portfolio",
    },
    demoBanner: "You are looking at a sample portfolio with approximate prices.",
    demoClear: "Delete it and start mine",
    summary: {
      label: "Portfolio summary",
      marketValue: "Net worth",
      marketValueHint: "cost of {value}",
      totalReturn: "Total return",
      totalReturnHint: "on {value} invested",
      unrealized: "Unrealized",
      realized: "Realized",
      income: "Dividends",
      cdi: "CDI over the period",
      cdiHint: "since {date}",
      cdiUnavailable: "unavailable right now",
      disclaimer: "Simple return: total return (unrealized + realized + dividends) ÷ total invested. CDI is a benchmark compounded since the first transaction.",
    },
    charts: {
      byAsset: "By asset",
      byAssetDescription: "Share of net worth",
      byClass: "By class",
      byClassDescription: "Stocks, REITs, ETFs, BDRs and crypto",
      others: "Others",
      classes: { stock: "Stocks", fii: "REITs (FIIs)", etf: "ETFs", bdr: "BDRs", crypto: "Crypto", other: "Others" },
    },
    tabs: { positions: "Positions", transactions: "Transactions" },
    positions: {
      asset: "Asset",
      quantity: "Qty",
      averagePrice: "Avg. price",
      price: "Price",
      day: "Day",
      value: "Value",
      result: "Return",
      weight: "Weight",
      noQuote: "no quote",
      oversold: "There are sales above the quantity bought — check this asset's transactions.",
      closedTitle: "Closed positions",
      closedDescription: "Assets fully sold",
      realized: "Realized",
      income: "Dividends",
    },
    transactions: {
      date: "Date",
      type: "Type",
      asset: "Asset",
      quantity: "Qty",
      price: "Price",
      total: "Total",
      remove: "Delete",
      removeLabel: "Delete {ticker} transaction on {date}",
      kinds: { buy: "Buy", sell: "Sell", bonus: "Split", merge: "Reverse split", income: "Dividend" },
    },
    form: {
      title: "Add transaction",
      description: "A buy, a sell or a dividend received.",
      kind: "Type",
      ticker: "Asset",
      tickerPlaceholder: "PETR4 or BTC",
      tickerInvalid: "Use a B3 ticker (PETR4, MXRF11) or a crypto symbol (BTC, ETH).",
      tickerHint: "B3 stocks, REITs and ETFs, or crypto (top 250 by market cap).",
      date: "Date",
      dateInvalid: "Enter a date up to today.",
      quantity: "Quantity",
      price: "Unit price (R$)",
      amount: "Amount received (R$)",
      fees: "Fees (R$)",
      positive: "Enter a value greater than zero.",
      total: "Transaction total",
      submit: "Add",
      cancel: "Cancel",
    },
    importer: {
      title: "Import from B3",
      description: "Use the Movements statement from B3's Investor Area: it includes buys, sells, dividends, splits and reverse splits.",
      steps: [
        "Sign in at investidor.b3.com.br",
        "Open Extratos → Movimentação",
        "Pick the period and download it as Excel (.xlsx), unedited",
      ],
      file: "B3 spreadsheet (.xlsx)",
      localOnly: "The file is read right here, in your browser.",
      reading: "Reading spreadsheet…",
      unknownFormat: "I couldn't recognize this spreadsheet. Use B3's Movements (or Trades) statement with its columns unchanged.",
      readError: "Couldn't read the file. It must be an .xlsx spreadsheet.",
      found: { one: "{n} transaction found", other: "{n} transactions found" },
      skipped: { one: "{n} row skipped", other: "{n} rows skipped" },
      skippedHint: "Fixed income, Treasury bonds, stock lending and events the portfolio doesn't handle yet are left out.",
      confirm: "Import",
      cancel: "Cancel",
      done: { one: "{n} transaction imported", other: "{n} transactions imported" },
      duplicates: { one: "{n} was already in the portfolio", other: "{n} were already in the portfolio" },
    },
    restore: {
      invalid: "Invalid backup file.",
      done: { one: "{n} transaction restored", other: "{n} transactions restored" },
    },
    market: {
      loading: "Fetching quotes…",
      error: "Couldn't refresh quotes right now — values are shown at cost.",
      missing: "No brapi quote for: {tickers}",
      updatedAt: "Quotes as of {time} (up to 15 min delay)",
      cryptoSource: "Crypto prices: CoinGecko",
    },
  },
  noSector: "No sector",
  // A brapi já envia os setores em inglês.
  sectors: {},
};
