import type { StocksDictionary } from "./types";

export const enUS: StocksDictionary = {
  meta: {
    title: "Kaiju Stocks — B3 stock quotes",
    description: "Browse Brazilian (B3) stocks: top gainers and losers, volume by sector and price history.",
  },
  layout: {
    skipToContent: "Skip to content",
    backToPortfolio: "Back to portfolio",
    backShort: "Portfolio",
    footer: "Quotes delayed by up to 15 minutes. Not investment advice.",
    dataSource: "Data: brapi.dev",
  },
  market: {
    title: "Market",
    subtitle: "Overview of the {n} most traded stocks and a searchable list of every listed ticker.",
    freeTickers: "History available without a token for:",
    summaryLabel: "Summary",
    up: "Up",
    down: "Down",
    ofMostTraded: "of the {n} most traded",
    averageChange: "Average change",
    averageChangeHint: "simple average of the day",
    totalVolume: "Total volume",
    totalVolumeHint: "shares traded",
    moversTitle: "Top gainers and losers",
    moversDescription: "Daily change among the most traded stocks",
    sectorsTitle: "Volume by sector",
    sectorsDescription: "Share of volume among the most traded stocks",
    others: "Others",
    allStocks: "All stocks",
    allStocksHint: "Click a stock to see its price history.",
  },
  filters: {
    searchPlaceholder: "Search ticker or company",
    searchLabel: "Search stocks",
    sectorLabel: "Filter by sector",
    allSectors: "All sectors",
  },
  table: {
    asset: "Stock",
    price: "Price",
    day: "Day",
    volume: "Volume",
    marketCap: "Market cap",
    sector: "Sector",
    empty: "No stocks match this filter.",
    pagination: "{total} stocks · page {page} of {pages}",
    paginationLabel: "Pagination",
    previous: "Previous",
    next: "Next",
  },
  detail: {
    back: "Back to market",
    updatedAt: "Updated {date}",
    indicators: "Indicators",
    open: "Open",
    previousClose: "Prev. close",
    dayRange: "Day low / high",
    yearRange: "52-week low / high",
    volume: "Volume",
    marketCap: "Market cap",
    pe: "P/E",
    eps: "EPS",
    quote: "Price",
    periodChange: "In period",
    min: "low",
    max: "high",
    rangeLabel: "Period",
    proRanges: "1Y and 5Y require brapi's Pro plan",
    tradedVolume: "Traded volume",
    noHistory: "No history for this period.",
    history: "History",
    lastSessions: "Last {n} trading sessions in the period",
    date: "Date",
    low: "Low",
    high: "High",
    close: "Close",
    needsToken: "{ticker} history requires a token",
    needsTokenDescription: "Without a token, brapi only serves details for {tickers}. Create a free token at brapi.dev and set BRAPI_TOKEN in the environment.",
    unavailable: "Couldn't load the quote",
    tryAgain: "Please try again in a moment.",
    ranges: { "5d": "5D", "1mo": "1M", "3mo": "3M", "1y": "1Y", "5y": "5Y" },
  },
  charts: { change: "Change", close: "Close", volume: "Volume" },
  states: {
    notFound: "Stock not found.",
    backToMarket: "Back to market",
    errorTitle: "Couldn't load the market",
    errorDescription: "brapi didn't respond. Please try again in a moment.",
    retry: "Try again",
  },
  noSector: "No sector",
  // A brapi já envia os setores em inglês.
  sectors: {},
};
