import type { StocksDictionary } from "./types";

export const esES: StocksDictionary = {
  meta: {
    title: "Kaiju Stocks — cotizaciones de la B3",
    description: "Consulta acciones de la B3: mayores alzas y bajas, volumen por sector e historial de precios.",
  },
  layout: {
    skipToContent: "Saltar al contenido",
    backToPortfolio: "Volver al portafolio",
    backShort: "Portafolio",
    footer: "Cotizaciones con hasta 15 minutos de retraso. No es una recomendación de inversión.",
    dataSource: "Datos: brapi.dev",
  },
  nav: { label: "Navegación de Kaiju Stocks", market: "Mercado", portfolio: "Cartera" },
  market: {
    title: "Mercado",
    subtitle: "Panorama de las {n} acciones más negociadas y consulta de todos los valores listados.",
    freeTickers: "Historial disponible sin token para:",
    summaryLabel: "Resumen",
    up: "Al alza",
    down: "A la baja",
    ofMostTraded: "de las {n} más negociadas",
    averageChange: "Variación media",
    averageChangeHint: "promedio simple del día",
    totalVolume: "Volumen total",
    totalVolumeHint: "acciones negociadas",
    moversTitle: "Mayores alzas y bajas",
    moversDescription: "Variación del día entre las más negociadas",
    sectorsTitle: "Volumen por sector",
    sectorsDescription: "Participación en el volumen de las más negociadas",
    others: "Otros",
    allStocks: "Todas las acciones",
    allStocksHint: "Haz clic en una acción para ver su historial.",
  },
  filters: {
    searchPlaceholder: "Buscar ticker o empresa",
    searchLabel: "Buscar acciones",
    sectorLabel: "Filtrar por sector",
    allSectors: "Todos los sectores",
  },
  table: {
    asset: "Activo",
    price: "Precio",
    day: "Día",
    volume: "Volumen",
    marketCap: "Valor de mercado",
    sector: "Sector",
    empty: "Ninguna acción coincide con este filtro.",
    pagination: "{total} activos · página {page} de {pages}",
    paginationLabel: "Paginación",
    previous: "Anterior",
    next: "Siguiente",
  },
  detail: {
    back: "Volver al mercado",
    updatedAt: "Actualizado el {date}",
    indicators: "Indicadores",
    open: "Apertura",
    previousClose: "Cierre anterior",
    dayRange: "Mín. / Máx. del día",
    yearRange: "Mín. / Máx. 52 sem.",
    volume: "Volumen",
    marketCap: "Valor de mercado",
    pe: "PER",
    eps: "BPA",
    quote: "Cotización",
    periodChange: "En el período",
    min: "mín.",
    max: "máx.",
    rangeLabel: "Período",
    proRanges: "1A y 5A disponibles en el plan Pro de brapi",
    tradedVolume: "Volumen negociado",
    noHistory: "Sin historial para este período.",
    history: "Historial",
    lastSessions: "Últimas {n} sesiones del período",
    date: "Fecha",
    low: "Mínimo",
    high: "Máximo",
    close: "Cierre",
    needsToken: "El historial de {ticker} requiere token",
    needsTokenDescription: "Sin token, brapi solo ofrece el detalle de {tickers}. Crea un token gratuito en brapi.dev y define BRAPI_TOKEN en el entorno.",
    unavailable: "No se pudo cargar la cotización",
    tryAgain: "Inténtalo de nuevo en unos instantes.",
    ranges: { "5d": "5D", "1mo": "1M", "3mo": "3M", "1y": "1A", "5y": "5A" },
  },
  charts: { change: "Variación", close: "Cierre", volume: "Volumen" },
  crypto: {
    title: "Criptomonedas",
    description: "Las mayores por capitalización, cotizadas en reales, con la variación de las últimas 24 horas.",
    moversTitle: "Mayores alzas y bajas (24h)",
    moversDescription: "Entre las {n} mayores por capitalización",
    topTitle: "Mayores por capitalización",
    topDescription: "Precio en reales y variación en 24 horas",
    rank: "#",
    asset: "Moneda",
    price: "Precio",
    change: "24h",
    marketCap: "Capitalización",
    source: "Datos de cripto: CoinGecko",
    track: "Seguirla en tu cartera",
  },
  states: {
    notFound: "Activo no encontrado.",
    backToMarket: "Volver al mercado",
    errorTitle: "No se pudo cargar el mercado",
    errorDescription: "brapi no respondió. Inténtalo de nuevo en unos instantes.",
    retry: "Reintentar",
  },
  portfolio: {
    meta: {
      title: "Cartera",
      description: "Sigue acciones, FII, ETF y cripto con precio medio, resultado, dividendos y comparación con el CDI — datos guardados solo en tu navegador.",
    },
    title: "Mi cartera",
    subtitle: "Precio medio, resultado, dividendos y comparación con el CDI de tus acciones, FII y ETF de la B3 y criptomonedas.",
    privacy: "Tus datos se quedan solo en este navegador — nada se envía a servidores.",
    actions: {
      add: "Añadir operación",
      import: "Importar de la B3",
      backup: "Copia de seguridad",
      export: "Exportar copia (JSON)",
      restore: "Restaurar copia",
      clear: "Borrar cartera",
      clearTitle: "¿Borrar la cartera?",
      clearDescription: "Se eliminarán todas las operaciones guardadas en este navegador. Exporta una copia antes si quieres conservarlas.",
      confirmClear: "Borrar todo",
      cancel: "Cancelar",
    },
    empty: {
      title: "Tu cartera está vacía",
      description: "Registra tus operaciones a mano, importa la hoja del Área del Inversor de la B3 o mira cómo queda con una cartera de ejemplo.",
      demo: "Ver cartera de ejemplo",
    },
    demoBanner: "Estás viendo una cartera de ejemplo, con precios aproximados.",
    demoClear: "Borrarla y empezar la mía",
    summary: {
      label: "Resumen de la cartera",
      marketValue: "Patrimonio",
      marketValueHint: "costo de {value}",
      totalReturn: "Resultado total",
      totalReturnHint: "sobre {value} invertidos",
      unrealized: "Abierto",
      realized: "Realizado",
      income: "Dividendos",
      cdi: "CDI en el período",
      cdiHint: "desde {date}",
      cdiUnavailable: "no disponible ahora",
      disclaimer: "Rentabilidad simple: resultado total (abierto + realizado + dividendos) ÷ total invertido. El CDI es una referencia acumulada desde la primera operación.",
    },
    charts: {
      byAsset: "Por activo",
      byAssetDescription: "Participación en el patrimonio",
      byClass: "Por clase",
      byClassDescription: "Acciones, FII, ETF, BDR y cripto",
      others: "Otros",
      classes: { stock: "Acciones", fii: "FII", etf: "ETF", bdr: "BDR", crypto: "Cripto", other: "Otros" },
    },
    tabs: { positions: "Posiciones", transactions: "Operaciones" },
    positions: {
      asset: "Activo",
      quantity: "Cant.",
      averagePrice: "Precio medio",
      price: "Cotización",
      day: "Día",
      value: "Valor",
      result: "Resultado",
      weight: "Cartera",
      noQuote: "sin cotización",
      oversold: "Hay ventas por encima de la cantidad comprada — revisa las operaciones de este activo.",
      closedTitle: "Posiciones cerradas",
      closedDescription: "Activos vendidos por completo",
      realized: "Realizado",
      income: "Dividendos",
    },
    transactions: {
      date: "Fecha",
      type: "Tipo",
      asset: "Activo",
      quantity: "Cant.",
      price: "Precio",
      total: "Total",
      remove: "Eliminar",
      removeLabel: "Eliminar operación de {ticker} del {date}",
      kinds: { buy: "Compra", sell: "Venta", bonus: "Desdoblamiento", merge: "Agrupamiento", income: "Dividendo" },
    },
    form: {
      title: "Añadir operación",
      description: "Una compra, una venta o un dividendo recibido.",
      kind: "Tipo",
      ticker: "Activo",
      tickerPlaceholder: "PETR4 o BTC",
      tickerInvalid: "Usa el código de la B3 (PETR4, MXRF11) o el símbolo de la cripto (BTC, ETH).",
      tickerHint: "Acciones, FII y ETF de la B3 o cripto (las 250 mayores por capitalización).",
      date: "Fecha",
      dateInvalid: "Indica una fecha hasta hoy.",
      quantity: "Cantidad",
      price: "Precio unitario (R$)",
      amount: "Importe recibido (R$)",
      fees: "Comisiones (R$)",
      positive: "Indica un valor mayor que cero.",
      total: "Total de la operación",
      submit: "Añadir",
      cancel: "Cancelar",
    },
    importer: {
      title: "Importar de la B3",
      description: "Usa el extracto de Movimientos del Área del Inversor: incluye compras, ventas, dividendos, desdoblamientos y agrupamientos.",
      steps: [
        "Entra en investidor.b3.com.br",
        "Abre Extratos → Movimentação",
        "Elige el período y descárgalo en Excel (.xlsx), sin editar",
      ],
      file: "Hoja de la B3 (.xlsx)",
      localOnly: "El archivo se lee aquí mismo, en tu navegador.",
      reading: "Leyendo hoja…",
      unknownFormat: "No reconocí esta hoja. Usa el extracto de Movimientos (o de Negociación) de la B3 sin cambiar las columnas.",
      readError: "No se pudo leer el archivo. Debe ser una hoja .xlsx.",
      found: { one: "{n} operación encontrada", other: "{n} operaciones encontradas" },
      skipped: { one: "{n} fila ignorada", other: "{n} filas ignoradas" },
      skippedHint: "Renta fija, Tesoro, préstamo de acciones y eventos que la cartera aún no trata quedan fuera.",
      confirm: "Importar",
      cancel: "Cancelar",
      done: { one: "{n} operación importada", other: "{n} operaciones importadas" },
      duplicates: { one: "{n} ya estaba en la cartera", other: "{n} ya estaban en la cartera" },
    },
    restore: {
      invalid: "Archivo de copia no válido.",
      done: { one: "{n} operación restaurada", other: "{n} operaciones restauradas" },
    },
    market: {
      loading: "Buscando cotizaciones…",
      error: "No se pudieron actualizar las cotizaciones ahora — los valores se muestran al costo.",
      missing: "Sin cotización en brapi para: {tickers}",
      updatedAt: "Cotizaciones de las {time} (retraso de hasta 15 min)",
      cryptoSource: "Precios de cripto: CoinGecko",
    },
  },
  noSector: "Sin sector",
  sectors: {
    "Retail Trade": "Comercio minorista",
    "Energy Minerals": "Petróleo y gas",
    "Health Services": "Servicios de salud",
    Utilities: "Servicios públicos",
    Finance: "Finanzas",
    "Consumer Services": "Servicios al consumidor",
    "Consumer Non-Durables": "Consumo no cíclico",
    "Non-Energy Minerals": "Minería y siderurgia",
    "Commercial Services": "Servicios comerciales",
    "Distribution Services": "Distribución",
    Transportation: "Transporte",
    "Technology Services": "Tecnología",
    "Process Industries": "Industria de procesos",
    Communications: "Telecomunicaciones",
    "Producer Manufacturing": "Bienes industriales",
    Miscellaneous: "Varios",
    "Electronic Technology": "Electrónica",
    "Industrial Services": "Servicios industriales",
    "Health Technology": "Tecnología de salud",
    "Consumer Durables": "Consumo cíclico",
  },
};
