import type { StocksDictionary } from "./types";

export const esES: StocksDictionary = {
  meta: {
    title: "Kaiju Stocks — cotizaciones de la B3",
    description: "Consulta acciones de la B3: mayores alzas y bajas, volumen por sector e historial de precios.",
  },
  layout: {
    skipToContent: "Saltar al contenido",
    backToPortfolio: "Volver al portafolio",
    backShort: "Portafolio",
    footer: "Cotizaciones con hasta 15 minutos de retraso. No es una recomendación de inversión.",
    dataSource: "Datos: brapi.dev",
  },
  market: {
    title: "Mercado",
    subtitle: "Panorama de las {n} acciones más negociadas y consulta de todos los valores listados.",
    freeTickers: "Historial disponible sin token para:",
    summaryLabel: "Resumen",
    up: "Al alza",
    down: "A la baja",
    ofMostTraded: "de las {n} más negociadas",
    averageChange: "Variación media",
    averageChangeHint: "promedio simple del día",
    totalVolume: "Volumen total",
    totalVolumeHint: "acciones negociadas",
    moversTitle: "Mayores alzas y bajas",
    moversDescription: "Variación del día entre las más negociadas",
    sectorsTitle: "Volumen por sector",
    sectorsDescription: "Participación en el volumen de las más negociadas",
    others: "Otros",
    allStocks: "Todas las acciones",
    allStocksHint: "Haz clic en una acción para ver su historial.",
  },
  filters: {
    searchPlaceholder: "Buscar ticker o empresa",
    searchLabel: "Buscar acciones",
    sectorLabel: "Filtrar por sector",
    allSectors: "Todos los sectores",
  },
  table: {
    asset: "Activo",
    price: "Precio",
    day: "Día",
    volume: "Volumen",
    marketCap: "Valor de mercado",
    sector: "Sector",
    empty: "Ninguna acción coincide con este filtro.",
    pagination: "{total} activos · página {page} de {pages}",
    paginationLabel: "Paginación",
    previous: "Anterior",
    next: "Siguiente",
  },
  detail: {
    back: "Volver al mercado",
    updatedAt: "Actualizado el {date}",
    indicators: "Indicadores",
    open: "Apertura",
    previousClose: "Cierre anterior",
    dayRange: "Mín. / Máx. del día",
    yearRange: "Mín. / Máx. 52 sem.",
    volume: "Volumen",
    marketCap: "Valor de mercado",
    pe: "PER",
    eps: "BPA",
    quote: "Cotización",
    periodChange: "En el período",
    min: "mín.",
    max: "máx.",
    rangeLabel: "Período",
    proRanges: "1A y 5A disponibles en el plan Pro de brapi",
    tradedVolume: "Volumen negociado",
    noHistory: "Sin historial para este período.",
    history: "Historial",
    lastSessions: "Últimas {n} sesiones del período",
    date: "Fecha",
    low: "Mínimo",
    high: "Máximo",
    close: "Cierre",
    needsToken: "El historial de {ticker} requiere token",
    needsTokenDescription: "Sin token, brapi solo ofrece el detalle de {tickers}. Crea un token gratuito en brapi.dev y define BRAPI_TOKEN en el entorno.",
    unavailable: "No se pudo cargar la cotización",
    tryAgain: "Inténtalo de nuevo en unos instantes.",
    ranges: { "5d": "5D", "1mo": "1M", "3mo": "3M", "1y": "1A", "5y": "5A" },
  },
  charts: { change: "Variación", close: "Cierre", volume: "Volumen" },
  states: {
    notFound: "Activo no encontrado.",
    backToMarket: "Volver al mercado",
    errorTitle: "No se pudo cargar el mercado",
    errorDescription: "brapi no respondió. Inténtalo de nuevo en unos instantes.",
    retry: "Reintentar",
  },
  noSector: "Sin sector",
  sectors: {
    "Retail Trade": "Comercio minorista",
    "Energy Minerals": "Petróleo y gas",
    "Health Services": "Servicios de salud",
    Utilities: "Servicios públicos",
    Finance: "Finanzas",
    "Consumer Services": "Servicios al consumidor",
    "Consumer Non-Durables": "Consumo no cíclico",
    "Non-Energy Minerals": "Minería y siderurgia",
    "Commercial Services": "Servicios comerciales",
    "Distribution Services": "Distribución",
    Transportation: "Transporte",
    "Technology Services": "Tecnología",
    "Process Industries": "Industria de procesos",
    Communications: "Telecomunicaciones",
    "Producer Manufacturing": "Bienes industriales",
    Miscellaneous: "Varios",
    "Electronic Technology": "Electrónica",
    "Industrial Services": "Servicios industriales",
    "Health Technology": "Tecnología de salud",
    "Consumer Durables": "Consumo cíclico",
  },
};
