import type { StocksDictionary } from "./types";

export const ptBR: StocksDictionary = {
  meta: {
    title: "Kaiju Stocks — cotações da B3",
    description: "Consulte ações da B3, maiores altas e quedas, volume por setor e histórico de preços.",
  },
  layout: {
    skipToContent: "Pular para o conteúdo",
    backToPortfolio: "Voltar ao portfólio",
    backShort: "Portfólio",
    footer: "Cotações com atraso de até 15 minutos. Não é recomendação de investimento.",
    dataSource: "Dados: brapi.dev",
  },
  market: {
    title: "Mercado",
    subtitle: "Panorama das {n} ações mais negociadas e consulta de todos os papéis listados.",
    freeTickers: "Histórico disponível sem token para:",
    summaryLabel: "Resumo",
    up: "Em alta",
    down: "Em queda",
    ofMostTraded: "de {n} mais negociadas",
    averageChange: "Variação média",
    averageChangeHint: "média simples do dia",
    totalVolume: "Volume total",
    totalVolumeHint: "ações negociadas",
    moversTitle: "Maiores altas e quedas",
    moversDescription: "Variação do dia entre as mais negociadas",
    sectorsTitle: "Volume por setor",
    sectorsDescription: "Participação no volume das mais negociadas",
    others: "Outros",
    allStocks: "Todas as ações",
    allStocksHint: "Clique em uma ação para ver o histórico.",
  },
  filters: {
    searchPlaceholder: "Buscar ticker ou empresa",
    searchLabel: "Buscar ações",
    sectorLabel: "Filtrar por setor",
    allSectors: "Todos os setores",
  },
  table: {
    asset: "Ativo",
    price: "Preço",
    day: "Dia",
    volume: "Volume",
    marketCap: "Valor de mercado",
    sector: "Setor",
    empty: "Nenhuma ação encontrada para esse filtro.",
    pagination: "{total} ativos · página {page} de {pages}",
    paginationLabel: "Paginação",
    previous: "Anterior",
    next: "Próxima",
  },
  detail: {
    back: "Voltar ao mercado",
    updatedAt: "Atualizado em {date}",
    indicators: "Indicadores",
    open: "Abertura",
    previousClose: "Fech. anterior",
    dayRange: "Mín. / Máx. dia",
    yearRange: "Mín. / Máx. 52 sem.",
    volume: "Volume",
    marketCap: "Valor de mercado",
    pe: "P/L",
    eps: "LPA",
    quote: "Cotação",
    periodChange: "No período",
    min: "mín.",
    max: "máx.",
    rangeLabel: "Período",
    proRanges: "1A e 5A disponíveis no plano Pro da brapi",
    tradedVolume: "Volume negociado",
    noHistory: "Sem histórico para esse período.",
    history: "Histórico",
    lastSessions: "Últimos {n} pregões do período",
    date: "Data",
    low: "Mínima",
    high: "Máxima",
    close: "Fechamento",
    needsToken: "Histórico de {ticker} precisa de token",
    needsTokenDescription: "Sem token, a brapi só libera o detalhe de {tickers}. Crie um token gratuito em brapi.dev e defina BRAPI_TOKEN no ambiente.",
    unavailable: "Não foi possível carregar a cotação",
    tryAgain: "Tente novamente em instantes.",
    ranges: { "5d": "5D", "1mo": "1M", "3mo": "3M", "1y": "1A", "5y": "5A" },
  },
  charts: { change: "Variação", close: "Fechamento", volume: "Volume" },
  states: {
    notFound: "Ativo não encontrado.",
    backToMarket: "Voltar ao mercado",
    errorTitle: "Não foi possível carregar o mercado",
    errorDescription: "A brapi não respondeu. Tente novamente em instantes.",
    retry: "Tentar novamente",
  },
  noSector: "Sem setor",
  sectors: {
    "Retail Trade": "Varejo",
    "Energy Minerals": "Petróleo e Gás",
    "Health Services": "Serviços de Saúde",
    Utilities: "Utilidades Públicas",
    Finance: "Financeiro",
    "Consumer Services": "Serviços ao Consumidor",
    "Consumer Non-Durables": "Consumo Não Cíclico",
    "Non-Energy Minerals": "Mineração e Siderurgia",
    "Commercial Services": "Serviços Comerciais",
    "Distribution Services": "Distribuição",
    Transportation: "Transporte",
    "Technology Services": "Tecnologia",
    "Process Industries": "Indústria de Processos",
    Communications: "Telecomunicações",
    "Producer Manufacturing": "Bens Industriais",
    Miscellaneous: "Diversos",
    "Electronic Technology": "Eletrônicos",
    "Industrial Services": "Serviços Industriais",
    "Health Technology": "Tecnologia em Saúde",
    "Consumer Durables": "Consumo Cíclico",
  },
};
