import type { StocksDictionary } from "./types";

export const ptBR: StocksDictionary = {
  meta: {
    title: "Kaiju Stocks — cotações da B3",
    description: "Consulte ações da B3, maiores altas e quedas, volume por setor e histórico de preços.",
  },
  layout: {
    skipToContent: "Pular para o conteúdo",
    backToPortfolio: "Voltar ao portfólio",
    backShort: "Portfólio",
    footer: "Cotações com atraso de até 15 minutos. Não é recomendação de investimento.",
    dataSource: "Dados: brapi.dev",
  },
  nav: { label: "Navegação do Kaiju Stocks", market: "Mercado", portfolio: "Carteira" },
  market: {
    title: "Mercado",
    subtitle: "Panorama das {n} ações mais negociadas e consulta de todos os papéis listados.",
    freeTickers: "Histórico disponível sem token para:",
    summaryLabel: "Resumo",
    up: "Em alta",
    down: "Em queda",
    ofMostTraded: "de {n} mais negociadas",
    averageChange: "Variação média",
    averageChangeHint: "média simples do dia",
    totalVolume: "Volume total",
    totalVolumeHint: "ações negociadas",
    moversTitle: "Maiores altas e quedas",
    moversDescription: "Variação do dia entre as mais negociadas",
    sectorsTitle: "Volume por setor",
    sectorsDescription: "Participação no volume das mais negociadas",
    others: "Outros",
    allStocks: "Todas as ações",
    allStocksHint: "Clique em uma ação para ver o histórico.",
  },
  filters: {
    searchPlaceholder: "Buscar ticker ou empresa",
    searchLabel: "Buscar ações",
    sectorLabel: "Filtrar por setor",
    allSectors: "Todos os setores",
  },
  table: {
    asset: "Ativo",
    price: "Preço",
    day: "Dia",
    volume: "Volume",
    marketCap: "Valor de mercado",
    sector: "Setor",
    empty: "Nenhuma ação encontrada para esse filtro.",
    pagination: "{total} ativos · página {page} de {pages}",
    paginationLabel: "Paginação",
    previous: "Anterior",
    next: "Próxima",
  },
  detail: {
    back: "Voltar ao mercado",
    updatedAt: "Atualizado em {date}",
    indicators: "Indicadores",
    open: "Abertura",
    previousClose: "Fech. anterior",
    dayRange: "Mín. / Máx. dia",
    yearRange: "Mín. / Máx. 52 sem.",
    volume: "Volume",
    marketCap: "Valor de mercado",
    pe: "P/L",
    eps: "LPA",
    quote: "Cotação",
    periodChange: "No período",
    min: "mín.",
    max: "máx.",
    rangeLabel: "Período",
    proRanges: "1A e 5A disponíveis no plano Pro da brapi",
    tradedVolume: "Volume negociado",
    noHistory: "Sem histórico para esse período.",
    history: "Histórico",
    lastSessions: "Últimos {n} pregões do período",
    date: "Data",
    low: "Mínima",
    high: "Máxima",
    close: "Fechamento",
    needsToken: "Histórico de {ticker} precisa de token",
    needsTokenDescription: "Sem token, a brapi só libera o detalhe de {tickers}. Crie um token gratuito em brapi.dev e defina BRAPI_TOKEN no ambiente.",
    unavailable: "Não foi possível carregar a cotação",
    tryAgain: "Tente novamente em instantes.",
    ranges: { "5d": "5D", "1mo": "1M", "3mo": "3M", "1y": "1A", "5y": "5A" },
  },
  charts: { change: "Variação", close: "Fechamento", volume: "Volume" },
  states: {
    notFound: "Ativo não encontrado.",
    backToMarket: "Voltar ao mercado",
    errorTitle: "Não foi possível carregar o mercado",
    errorDescription: "A brapi não respondeu. Tente novamente em instantes.",
    retry: "Tentar novamente",
  },
  portfolio: {
    meta: {
      title: "Carteira",
      description: "Acompanhe ações, FIIs, ETFs e cripto com preço médio, resultado, proventos e comparação com o CDI — dados salvos só no seu navegador.",
    },
    title: "Minha carteira",
    subtitle: "Preço médio, resultado, proventos e comparação com o CDI das suas ações, FIIs, ETFs e criptomoedas.",
    privacy: "Seus dados ficam só neste navegador — nada é enviado para servidores.",
    actions: {
      add: "Adicionar operação",
      import: "Importar da B3",
      backup: "Backup",
      export: "Exportar backup (JSON)",
      restore: "Restaurar backup",
      clear: "Apagar carteira",
      clearTitle: "Apagar a carteira?",
      clearDescription: "Todas as operações salvas neste navegador serão removidas. Exporte um backup antes se quiser guardar.",
      confirmClear: "Apagar tudo",
      cancel: "Cancelar",
    },
    empty: {
      title: "Sua carteira está vazia",
      description: "Lance suas operações à mão, importe a planilha da Área do Investidor da B3 ou veja como fica com uma carteira de exemplo.",
      demo: "Ver carteira de exemplo",
    },
    demoBanner: "Você está vendo uma carteira de exemplo, com preços aproximados.",
    demoClear: "Apagar e começar a minha",
    summary: {
      label: "Resumo da carteira",
      marketValue: "Patrimônio",
      marketValueHint: "custo de {value}",
      totalReturn: "Resultado total",
      totalReturnHint: "sobre {value} aplicados",
      unrealized: "Em aberto",
      realized: "Realizado",
      income: "Proventos",
      cdi: "CDI no período",
      cdiHint: "desde {date}",
      cdiUnavailable: "indisponível agora",
      disclaimer: "Rentabilidade simples: resultado total (em aberto + realizado + proventos) ÷ total aplicado. O CDI é uma referência acumulada desde a primeira operação.",
    },
    charts: {
      byAsset: "Por ativo",
      byAssetDescription: "Participação no patrimônio",
      byClass: "Por classe",
      byClassDescription: "Ações, FIIs, ETFs, BDRs e cripto",
      others: "Outros",
      classes: { stock: "Ações", fii: "FIIs", etf: "ETFs", bdr: "BDRs", crypto: "Cripto", other: "Outros" },
    },
    tabs: { positions: "Posições", transactions: "Operações" },
    positions: {
      asset: "Ativo",
      quantity: "Qtd.",
      averagePrice: "Preço médio",
      price: "Cotação",
      day: "Dia",
      value: "Valor",
      result: "Resultado",
      weight: "Carteira",
      noQuote: "sem cotação",
      oversold: "Há vendas acima da quantidade comprada — confira as operações deste ativo.",
      closedTitle: "Posições encerradas",
      closedDescription: "Ativos já vendidos por completo",
      realized: "Realizado",
      income: "Proventos",
    },
    transactions: {
      date: "Data",
      type: "Tipo",
      asset: "Ativo",
      quantity: "Qtd.",
      price: "Preço",
      total: "Total",
      remove: "Excluir",
      removeLabel: "Excluir operação de {ticker} em {date}",
      kinds: { buy: "Compra", sell: "Venda", bonus: "Desdobro", merge: "Grupamento", income: "Provento" },
    },
    form: {
      title: "Adicionar operação",
      description: "Compra, venda ou provento recebido.",
      kind: "Tipo",
      ticker: "Ativo",
      tickerPlaceholder: "PETR4 ou BTC",
      tickerInvalid: "Use o código da B3 (PETR4, MXRF11) ou o símbolo da cripto (BTC, ETH).",
      tickerHint: "Ações, FIIs e ETFs da B3 ou cripto (as 250 maiores por valor de mercado).",
      date: "Data",
      dateInvalid: "Informe uma data até hoje.",
      quantity: "Quantidade",
      price: "Preço unitário (R$)",
      amount: "Valor recebido (R$)",
      fees: "Taxas (R$)",
      positive: "Informe um valor maior que zero.",
      total: "Total da operação",
      submit: "Adicionar",
      cancel: "Cancelar",
    },
    importer: {
      title: "Importar da B3",
      description: "Use o extrato de Movimentação da Área do Investidor: ele traz compras, vendas, proventos, desdobros e grupamentos.",
      steps: [
        "Entre em investidor.b3.com.br",
        "Abra Extratos → Movimentação",
        "Escolha o período e baixe em Excel (.xlsx), sem editar",
      ],
      file: "Planilha da B3 (.xlsx)",
      localOnly: "O arquivo é lido aqui mesmo, no seu navegador.",
      reading: "Lendo planilha…",
      unknownFormat: "Não reconheci essa planilha. Use o extrato de Movimentação (ou de Negociação) da B3, sem alterar as colunas.",
      readError: "Não foi possível ler o arquivo. Ele precisa ser uma planilha .xlsx.",
      found: { one: "{n} operação encontrada", other: "{n} operações encontradas" },
      skipped: { one: "{n} linha ignorada", other: "{n} linhas ignoradas" },
      skippedHint: "Renda fixa, Tesouro, aluguel de ações e eventos que a carteira ainda não trata ficam de fora.",
      confirm: "Importar",
      cancel: "Cancelar",
      done: { one: "{n} operação importada", other: "{n} operações importadas" },
      duplicates: { one: "{n} já estava na carteira", other: "{n} já estavam na carteira" },
    },
    restore: {
      invalid: "Arquivo de backup inválido.",
      done: { one: "{n} operação restaurada", other: "{n} operações restauradas" },
    },
    market: {
      loading: "Buscando cotações…",
      error: "Não foi possível atualizar as cotações agora — os valores estão pelo custo.",
      missing: "Sem cotação na brapi para: {tickers}",
      updatedAt: "Cotações das {time} (atraso de até 15 min)",
      cryptoSource: "Preços de cripto: CoinGecko",
    },
  },
  noSector: "Sem setor",
  sectors: {
    "Retail Trade": "Varejo",
    "Energy Minerals": "Petróleo e Gás",
    "Health Services": "Serviços de Saúde",
    Utilities: "Utilidades Públicas",
    Finance: "Financeiro",
    "Consumer Services": "Serviços ao Consumidor",
    "Consumer Non-Durables": "Consumo Não Cíclico",
    "Non-Energy Minerals": "Mineração e Siderurgia",
    "Commercial Services": "Serviços Comerciais",
    "Distribution Services": "Distribuição",
    Transportation: "Transporte",
    "Technology Services": "Tecnologia",
    "Process Industries": "Indústria de Processos",
    Communications: "Telecomunicações",
    "Producer Manufacturing": "Bens Industriais",
    Miscellaneous: "Diversos",
    "Electronic Technology": "Eletrônicos",
    "Industrial Services": "Serviços Industriais",
    "Health Technology": "Tecnologia em Saúde",
    "Consumer Durables": "Consumo Cíclico",
  },
};
