/**
 * Conjunto curado de ícones do Design System.
 *
 * Reexporta apenas os ícones efetivamente usados pelos componentes de
 * `@godzilla/ui` (mais alguns de uso comum em produtos), em vez de expor a
 * biblioteca `lucide-react` inteira — mantém a superfície de API do Design
 * System sob controle e evita que cada app escolha um ícone diferente para o
 * mesmo conceito (ex.: "fechar").
 */
import type { LucideIcon, LucideProps } from "lucide-react";

export type { LucideIcon, LucideProps as IconProps };

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Banknote,
  BarChart3,
  BookOpen,
  Boxes,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clock,
  CodeXml,
  Copy,
  CreditCard,
  Disc3,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck2,
  FileSpreadsheet,
  FlaskConical,
  GitBranch,
  Globe,
  Headphones,
  History,
  Info,
  KeyRound,
  Keyboard,
  LayoutDashboard,
  Linkedin,
  ListMusic,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  Mic2,
  Minus,
  Moon,
  MoreHorizontal,
  Music,
  Package,
  Palette,
  Pencil,
  Play,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  ScanBarcode,
  Search,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Sun,
  Trash2,
  Undo2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Webhook,
  X,
} from "lucide-react";

export { FlagBR, FlagES, FlagUS, type FlagProps } from "./flags";
