import type { SpotifyDictionary } from "./types";

export const enUS: SpotifyDictionary = {
  meta: { description: "Explore your Spotify listening stats." },
  common: {
    skipToContent: "Skip to content",
    backToPortfolio: "Back to portfolio",
    backShort: "Portfolio",
    footer: "GODZILLA Spotify Stats is an independent project, not affiliated with or endorsed by Spotify or Last.fm.",
    dataBySpotify: "Data by Spotify",
    poweredByLastfm: "Powered by Last.fm",
  },
  ranges: {
    short_term: { label: "Last 4 weeks", short: "4 weeks" },
    medium_term: { label: "Last 6 months", short: "6 months" },
    long_term: { label: "Last year", short: "1 year" },
  },
  rangeLabel: "Time range",
  nav: { label: "Dashboard", overview: "Overview", artists: "Top Artists", tracks: "Top Tracks", recent: "Recently Played" },
  header: {
    badges: { showcase: "Live showcase", lastfm: "Last.fm", demo: "Demo" },
    logout: { live: "Logout", showcase: "Exit showcase", lastfm: "Exit Last.fm", demo: "Exit demo" },
    fallbackName: "Spotify listener",
  },
  banner: {
    showcase: "You're viewing **{name}'s real Spotify stats**, updated live.",
    lastfm: "Stats from **Last.fm** for **{name}**, built from their scrobbles.",
    demo: "You're exploring **demo data**.",
    connect: "Connect your Spotify",
    suffix: "to see your own stats.",
    ownerFallback: "the owner",
  },
  landing: {
    badge: "Spotify Web API · OAuth PKCE · Next.js",
    titleTop: "YOUR MUSIC.",
    titleBottom: "YOUR STATS.",
    subtitle: "Discover your Spotify listening habits.",
    openDashboard: "Open dashboard",
    connect: "Connect Spotify",
    exploreShowcase: "Explore Douglas's live stats",
    viewDemo: "View Demo",
    readOnly: "Read-only access · we never post, follow or change anything on your account.",
    lastfmHint: "Not invited? Use your Last.fm username →",
    previewLabel: "Dashboard preview",
    previewGenres: "Genre Distribution",
    previewGenresDescription: "Derived from your top artists",
    featuresTitle: "Everything the APIs can tell you",
    features: [
      { title: "Top Artists", description: "Your most-played artists over the last 4 weeks, 6 months or year, with genres and links." },
      { title: "Top Tracks", description: "A ranked list of your favourite songs with covers, albums and durations." },
      { title: "Recently Played", description: "A timeline of your last 50 plays, grouped by day in your own time zone." },
      { title: "Music Insights", description: "Genres, eras, artists across your top tracks and a live now-playing card." },
    ],
    limitations:
      "Stats are limited to what the APIs provide: top items for three time ranges and your recent plays. Spotify doesn't send genres to apps like this one — they come from Last.fm tags when available. This is not a Wrapped replacement.",
    ctaTitle: "Connect your Spotify",
    ctaDescription: "See your own top artists, tracks and genres in seconds — or explore without logging in first.",
    loginErrors: {
      access_denied: "You cancelled the Spotify authorization. Connect again whenever you're ready.",
      state_mismatch: "The login request couldn't be verified. Please try connecting again.",
      auth_failed: "We couldn't complete the Spotify login. Please try again.",
      not_allowlisted:
        "This Spotify account isn't allow-listed. The app runs in Spotify's Development Mode (limited to invited users) — try the demo or Last.fm instead.",
      session_expired: "Your session ended. Connect Spotify again or explore the demo.",
      not_configured: "Spotify login isn't configured on this deployment yet — explore the demo instead.",
    },
    lastfmErrors: {
      lastfm_not_found: "We couldn't find that Last.fm user. Check the spelling.",
      lastfm_private: "This Last.fm profile is private.",
      lastfm_unavailable: "Last.fm isn't responding right now. Try again in a moment.",
      lastfm_not_configured: "Last.fm isn't configured on this deployment yet.",
    },
  },
  lastfmForm: {
    eyebrow: "No invite needed",
    title: "Use your Last.fm",
    description:
      "Spotify only lets invited accounts log in to this app. If you scrobble your Spotify plays to {link}, type your username to see your stats — with genres from Last.fm tags.",
    label: "Last.fm username",
    placeholder: "e.g. rj",
    submit: "See stats",
    sectionLabel: "Use Last.fm",
  },
  overview: {
    title: "Overview",
    description: "Your listening at a glance · {range}",
    highlightsLabel: "Highlights",
    topArtist: "Top artist",
    topTrack: "Top track",
    topGenre: "Top genre",
    topEra: "Top era",
    recentlyPlayed: "Recently played",
    noData: "No data yet",
    nothingYet: "Nothing yet",
    unknown: "Unknown",
    followers: "{n} followers",
    inTopTracks: "In {n} of your top tracks",
    ofTopArtists: "{n} of {total} top artists",
    ofTopTracks: "{n} of your top {total} tracks",
    noReleaseDates: "No release dates available",
    genreTitle: "Genre Distribution",
    genreDescription: "Derived from {source} of your top {n} artists — not your full listening history.",
    genreSourceFallback: "the genres",
    genreSources: { lastfm: "Last.fm tags", spotify: "Spotify genres" },
    decadeTitle: "Your music by decade",
    decadeDescription: "Release year of your top {n} tracks.",
    artistsTitle: "Artists in your top tracks",
    artistsDescription: "How many of your top {n} tracks feature each artist.",
    tracksLabel: "Tracks",
    emptyTitle: "No top tracks yet",
    emptyDescription: "Listen to more music and check back later — or try a longer period.",
    justNow: "just now",
    minutesAgo: "{n} min ago",
    hoursAgo: "{n} h ago",
    daysAgo: "{n} d ago",
  },
  profile: {
    title: "Your Music Profile",
    artistsAnalyzed: "Artists analyzed",
    tracksAnalyzed: "Tracks analyzed",
    topArtist: "Top artist",
    topTrack: "Top track",
    topGenre: "Most common genre",
    genresDiscovered: "Genres discovered",
    favouriteEra: "Favourite era",
    newestRelease: "Newest release",
    oldestRelease: "Oldest release",
    explicitTracks: "Explicit tracks",
    averageLength: "Avg. track length",
  },
  nowPlaying: {
    label: "Now playing",
    paused: "Paused",
    nothing: "Nothing playing right now",
    hint: "Play something and it shows up here.",
    progress: "Playback progress",
  },
  artists: {
    title: "Top Artists",
    description: "{n} artists · {range}",
    top3: "Top 3 artists",
    more: "More top artists",
    plays: { one: "{n} play", other: "{n} plays" },
    followers: "{n} followers",
    popularity: "Popularity {n}",
    emptyTitle: "No top artists yet",
    emptyDescription: "There isn't enough listening history for this period. Try a longer range.",
    popularityTitle: "Artist Popularity",
    popularityDescription: "Spotify's popularity index (0–100) for your top 10 artists.",
    popularityLabel: "Popularity",
  },
  tracks: {
    title: "Top Tracks",
    description: "{n} tracks · {range}",
    cover: "Cover",
    track: "Track",
    artist: "Artist",
    album: "Album",
    plays: "Plays",
    popularity: "Popularity",
    duration: "Duration",
    playsCount: { one: "{n} play", other: "{n} plays" },
    coverAlt: "{name} cover",
    emptyTitle: "No top tracks yet",
    emptyDescription: "There isn't enough listening history for this period. Try a longer range.",
  },
  recent: {
    title: "Recently Played",
    descriptionSpotify: "Your last 50 plays — the most Spotify's API makes available.",
    descriptionLastfm: "Your last 50 scrobbles on Last.fm.",
    today: "Today",
    yesterday: "Yesterday",
    emptyTitle: "No listening history yet",
    emptyDescription: "Play some music and your recent tracks will show up here.",
  },
  charts: {
    artistsCount: { one: "{n} artist", other: "{n} artists" },
    tracksCount: { one: "{n} track", other: "{n} tracks" },
  },
  errors: {
    unauthorized: { title: "Your session expired", description: "Connect your Spotify account again to keep exploring your stats." },
    forbidden: {
      title: "Access denied",
      description: "This app runs in Spotify's Development Mode, so only allow-listed accounts can connect. Try the demo instead.",
    },
    rate_limited: { title: "Too many requests", description: "The service is limiting requests right now. Wait a few seconds and try again." },
    unavailable: { title: "Service unavailable", description: "The music API is not responding at the moment. Please try again shortly." },
    timeout: { title: "The request took too long", description: "The request timed out. Check your connection and try again." },
    network: { title: "Connection problem", description: "We couldn't reach the music API. Check your connection and try again." },
    not_found: { title: "User not found", description: "We couldn't find that Last.fm user. Check the username and try again." },
    invalid_response: { title: "Unexpected response", description: "The music service answered in a format we didn't expect. We've logged the issue — please try again shortly." },
    unknown: { title: "Something went wrong", description: "An unexpected error happened while loading your stats. Please try again." },
    reconnect: "Reconnect Spotify",
    viewDemo: "View demo",
    tryAgain: "Try again",
    boundaryTitle: "Something went wrong",
    boundaryDescription: "We couldn't load this page. Please try again in a moment.",
  },
};
