import type { SpotifyDictionary } from "./types";

export const esES: SpotifyDictionary = {
  meta: { description: "Visualiza tus estadísticas musicales de Spotify." },
  common: {
    skipToContent: "Saltar al contenido",
    backToPortfolio: "Volver al portafolio",
    backShort: "Portafolio",
    footer: "GODZILLA Spotify Stats es un proyecto independiente, sin afiliación ni respaldo de Spotify o Last.fm.",
    dataBySpotify: "Datos de Spotify",
    poweredByLastfm: "Con tecnología de Last.fm",
  },
  ranges: {
    short_term: { label: "Últimas 4 semanas", short: "4 semanas" },
    medium_term: { label: "Últimos 6 meses", short: "6 meses" },
    long_term: { label: "Último año", short: "1 año" },
  },
  rangeLabel: "Período",
  nav: { label: "Panel", overview: "Resumen", artists: "Top artistas", tracks: "Top canciones", recent: "Escuchadas recientemente" },
  header: {
    badges: { showcase: "Vitrina en vivo", lastfm: "Last.fm", demo: "Demo" },
    logout: { live: "Cerrar sesión", showcase: "Salir de la vitrina", lastfm: "Salir de Last.fm", demo: "Salir del demo" },
    fallbackName: "Oyente de Spotify",
  },
  banner: {
    showcase: "Estás viendo las **estadísticas reales de Spotify de {name}**, actualizadas en vivo.",
    lastfm: "Estadísticas de **Last.fm** de **{name}**, a partir de sus scrobbles.",
    demo: "Estás explorando **datos de demostración**.",
    connect: "Conecta tu Spotify",
    suffix: "para ver las tuyas.",
    ownerFallback: "el dueño del sitio",
  },
  landing: {
    badge: "Spotify Web API · OAuth PKCE · Next.js",
    titleTop: "TU MÚSICA.",
    titleBottom: "TUS NÚMEROS.",
    subtitle: "Descubre tus hábitos musicales en Spotify.",
    openDashboard: "Abrir panel",
    connect: "Conectar Spotify",
    exploreShowcase: "Ver las estadísticas de Douglas",
    viewDemo: "Ver demo",
    readOnly: "Acceso de solo lectura · nunca publicamos, seguimos ni cambiamos nada en tu cuenta.",
    lastfmHint: "¿Sin invitación? Usa tu usuario de Last.fm →",
    previewLabel: "Vista previa del panel",
    previewGenres: "Distribución de géneros",
    previewGenresDescription: "A partir de tus artistas top",
    featuresTitle: "Todo lo que las APIs pueden contar",
    features: [
      { title: "Top artistas", description: "Tus artistas más escuchados en las últimas 4 semanas, 6 meses o el último año, con géneros y enlaces." },
      { title: "Top canciones", description: "Ranking de tus canciones favoritas con portadas, álbumes y duraciones." },
      { title: "Escuchadas recientemente", description: "Línea de tiempo de tus últimas 50 canciones, agrupadas por día en tu zona horaria." },
      { title: "Insights musicales", description: "Géneros, épocas, artistas en tus canciones top y lo que suena ahora mismo." },
    ],
    limitations:
      "Las estadísticas se limitan a lo que ofrecen las APIs: tops para tres períodos y tus reproducciones recientes. Spotify no envía géneros a apps como esta: provienen de las etiquetas de Last.fm cuando están disponibles. Esto no reemplaza al Wrapped.",
    ctaTitle: "Conecta tu Spotify",
    ctaDescription: "Mira tus artistas, canciones y géneros top en segundos — o explora primero sin iniciar sesión.",
    loginErrors: {
      access_denied: "Cancelaste la autorización de Spotify. Conéctate de nuevo cuando quieras.",
      state_mismatch: "No se pudo verificar la solicitud de inicio de sesión. Intenta conectarte de nuevo.",
      auth_failed: "No pudimos completar el inicio de sesión con Spotify. Inténtalo de nuevo.",
      not_allowlisted:
        "Esta cuenta de Spotify no está habilitada. La app funciona en el Development Mode de Spotify (solo cuentas invitadas): usa el demo o Last.fm.",
      session_expired: "Tu sesión terminó. Conecta Spotify de nuevo o explora el demo.",
      not_configured: "El inicio de sesión con Spotify aún no está configurado en este entorno: explora el demo.",
    },
    lastfmErrors: {
      lastfm_not_found: "No encontramos ese usuario de Last.fm. Revisa cómo está escrito.",
      lastfm_private: "Este perfil de Last.fm es privado.",
      lastfm_unavailable: "Last.fm no responde en este momento. Inténtalo de nuevo en unos instantes.",
      lastfm_not_configured: "Last.fm aún no está configurado en este entorno.",
    },
  },
  lastfmForm: {
    eyebrow: "Sin invitación",
    title: "Usa tu Last.fm",
    description:
      "Spotify solo permite iniciar sesión en esta app a cuentas invitadas. Si registras lo que escuchas en Spotify en {link}, escribe tu usuario para ver tus estadísticas, con géneros de las etiquetas de Last.fm.",
    label: "Usuario de Last.fm",
    placeholder: "p. ej. rj",
    submit: "Ver estadísticas",
    sectionLabel: "Usar Last.fm",
  },
  overview: {
    title: "Resumen",
    description: "Tu música de un vistazo · {range}",
    highlightsLabel: "Destacados",
    topArtist: "Artista top",
    topTrack: "Canción top",
    topGenre: "Género top",
    topEra: "Época top",
    recentlyPlayed: "Escuchada recientemente",
    noData: "Aún no hay datos",
    nothingYet: "Nada aún",
    unknown: "Desconocida",
    followers: "{n} seguidores",
    inTopTracks: "En {n} de tus canciones top",
    ofTopArtists: "{n} de {total} artistas top",
    ofTopTracks: "{n} de tus {total} canciones top",
    noReleaseDates: "Sin fechas de lanzamiento",
    genreTitle: "Distribución de géneros",
    genreDescription: "A partir de {source} de tus {n} artistas top, no de todo tu historial.",
    genreSourceFallback: "los géneros",
    genreSources: { lastfm: "las etiquetas de Last.fm", spotify: "los géneros de Spotify" },
    decadeTitle: "Tu música por década",
    decadeDescription: "Año de lanzamiento de tus {n} canciones top.",
    artistsTitle: "Artistas en tus canciones top",
    artistsDescription: "En cuántas de tus {n} canciones top aparece cada artista.",
    tracksLabel: "Canciones",
    emptyTitle: "Aún no hay canciones top",
    emptyDescription: "Escucha más música y vuelve más tarde, o prueba un período más largo.",
    justNow: "ahora",
    minutesAgo: "hace {n} min",
    hoursAgo: "hace {n} h",
    daysAgo: "hace {n} d",
  },
  profile: {
    title: "Tu perfil musical",
    artistsAnalyzed: "Artistas analizados",
    tracksAnalyzed: "Canciones analizadas",
    topArtist: "Artista top",
    topTrack: "Canción top",
    topGenre: "Género más común",
    genresDiscovered: "Géneros descubiertos",
    favouriteEra: "Época favorita",
    newestRelease: "Lanzamiento más reciente",
    oldestRelease: "Lanzamiento más antiguo",
    explicitTracks: "Canciones explícitas",
    averageLength: "Duración media",
  },
  nowPlaying: {
    label: "Sonando ahora",
    paused: "En pausa",
    nothing: "No suena nada ahora",
    hint: "Pon algo a sonar y aparecerá aquí.",
    progress: "Progreso de la canción",
  },
  artists: {
    title: "Top artistas",
    description: "{n} artistas · {range}",
    top3: "Top 3 artistas",
    more: "Más artistas top",
    plays: { one: "{n} reproducción", other: "{n} reproducciones" },
    followers: "{n} seguidores",
    popularity: "Popularidad {n}",
    emptyTitle: "Aún no hay artistas top",
    emptyDescription: "No hay historial suficiente para este período. Prueba uno más largo.",
    popularityTitle: "Popularidad de los artistas",
    popularityDescription: "Índice de popularidad de Spotify (0–100) de tus 10 artistas top.",
    popularityLabel: "Popularidad",
  },
  tracks: {
    title: "Top canciones",
    description: "{n} canciones · {range}",
    cover: "Portada",
    track: "Canción",
    artist: "Artista",
    album: "Álbum",
    plays: "Reproducciones",
    popularity: "Popularidad",
    duration: "Duración",
    playsCount: { one: "{n} reproducción", other: "{n} reproducciones" },
    coverAlt: "Portada de {name}",
    emptyTitle: "Aún no hay canciones top",
    emptyDescription: "No hay historial suficiente para este período. Prueba uno más largo.",
  },
  recent: {
    title: "Escuchadas recientemente",
    descriptionSpotify: "Tus últimas 50 canciones: lo máximo que ofrece la API de Spotify.",
    descriptionLastfm: "Tus últimos 50 scrobbles en Last.fm.",
    today: "Hoy",
    yesterday: "Ayer",
    emptyTitle: "Aún no hay historial",
    emptyDescription: "Escucha algo de música y tus canciones recientes aparecerán aquí.",
  },
  charts: {
    artistsCount: { one: "{n} artista", other: "{n} artistas" },
    tracksCount: { one: "{n} canción", other: "{n} canciones" },
  },
  errors: {
    unauthorized: { title: "Tu sesión expiró", description: "Conecta tu cuenta de Spotify de nuevo para seguir explorando." },
    forbidden: {
      title: "Acceso denegado",
      description: "Esta app funciona en el Development Mode de Spotify, así que solo las cuentas invitadas pueden conectarse. Prueba el demo.",
    },
    rate_limited: { title: "Demasiadas solicitudes", description: "El servicio está limitando las solicitudes. Espera unos segundos e inténtalo de nuevo." },
    unavailable: { title: "Servicio no disponible", description: "La API de música no responde en este momento. Inténtalo de nuevo en breve." },
    timeout: { title: "La solicitud tardó demasiado", description: "Se agotó el tiempo. Revisa tu conexión e inténtalo de nuevo." },
    network: { title: "Problema de conexión", description: "No pudimos contactar con la API de música. Revisa tu conexión e inténtalo de nuevo." },
    not_found: { title: "Usuario no encontrado", description: "No encontramos ese usuario de Last.fm. Revisa el nombre e inténtalo de nuevo." },
    invalid_response: { title: "Respuesta inesperada", description: "El servicio de música respondió en un formato que no esperábamos. Ya registramos el problema: inténtalo de nuevo en unos instantes." },
    unknown: { title: "Algo salió mal", description: "Ocurrió un error inesperado al cargar tus estadísticas. Inténtalo de nuevo." },
    reconnect: "Reconectar Spotify",
    viewDemo: "Ver demo",
    tryAgain: "Reintentar",
    boundaryTitle: "Algo salió mal",
    boundaryDescription: "No pudimos cargar esta página. Inténtalo de nuevo en unos instantes.",
  },
};
