import type { SpotifyDictionary } from "./types";

export const ptBR: SpotifyDictionary = {
  meta: { description: "Visualize suas estatísticas musicais do Spotify." },
  common: {
    skipToContent: "Pular para o conteúdo",
    backToPortfolio: "Voltar ao portfólio",
    backShort: "Portfólio",
    footer: "GODZILLA Spotify Stats é um projeto independente, sem vínculo nem endosso do Spotify ou do Last.fm.",
    dataBySpotify: "Dados do Spotify",
    poweredByLastfm: "Com tecnologia Last.fm",
  },
  ranges: {
    short_term: { label: "Últimas 4 semanas", short: "4 semanas" },
    medium_term: { label: "Últimos 6 meses", short: "6 meses" },
    long_term: { label: "Último ano", short: "1 ano" },
  },
  rangeLabel: "Período",
  nav: { label: "Dashboard", overview: "Visão geral", artists: "Top artistas", tracks: "Top músicas", recent: "Tocadas recentemente" },
  header: {
    badges: { showcase: "Vitrine ao vivo", lastfm: "Last.fm", demo: "Demo" },
    logout: { live: "Sair", showcase: "Sair da vitrine", lastfm: "Sair do Last.fm", demo: "Sair do demo" },
    fallbackName: "Ouvinte do Spotify",
  },
  banner: {
    showcase: "Você está vendo as **estatísticas reais do Spotify de {name}**, atualizadas ao vivo.",
    lastfm: "Estatísticas do **Last.fm** de **{name}**, a partir dos scrobbles.",
    demo: "Você está explorando **dados de demonstração**.",
    connect: "Conecte seu Spotify",
    suffix: "para ver as suas.",
    ownerFallback: "o dono do site",
  },
  landing: {
    badge: "Spotify Web API · OAuth PKCE · Next.js",
    titleTop: "SUA MÚSICA.",
    titleBottom: "SEUS NÚMEROS.",
    subtitle: "Descubra seus hábitos musicais no Spotify.",
    openDashboard: "Abrir dashboard",
    connect: "Conectar Spotify",
    exploreShowcase: "Ver as estatísticas do Douglas",
    viewDemo: "Ver demo",
    readOnly: "Acesso somente leitura · nunca publicamos, seguimos ou alteramos nada na sua conta.",
    lastfmHint: "Sem convite? Use seu usuário do Last.fm →",
    previewLabel: "Prévia do dashboard",
    previewGenres: "Distribuição de gêneros",
    previewGenresDescription: "A partir dos seus top artistas",
    featuresTitle: "Tudo o que as APIs podem contar",
    features: [
      { title: "Top artistas", description: "Seus artistas mais ouvidos nas últimas 4 semanas, 6 meses ou no último ano, com gêneros e links." },
      { title: "Top músicas", description: "Ranking das suas músicas favoritas com capas, álbuns e durações." },
      { title: "Tocadas recentemente", description: "Linha do tempo das suas últimas 50 músicas, agrupadas por dia no seu fuso horário." },
      { title: "Insights musicais", description: "Gêneros, épocas, artistas nas suas top músicas e o que está tocando agora." },
    ],
    limitations:
      "As estatísticas se limitam ao que as APIs oferecem: tops para três períodos e suas músicas recentes. A Spotify não envia gêneros para apps como este — eles vêm das tags do Last.fm quando disponíveis. Isto não substitui o Wrapped.",
    ctaTitle: "Conecte seu Spotify",
    ctaDescription: "Veja seus top artistas, músicas e gêneros em segundos — ou explore primeiro sem fazer login.",
    loginErrors: {
      access_denied: "Você cancelou a autorização do Spotify. Conecte de novo quando quiser.",
      state_mismatch: "Não foi possível verificar o pedido de login. Tente conectar novamente.",
      auth_failed: "Não conseguimos concluir o login com o Spotify. Tente novamente.",
      not_allowlisted:
        "Esta conta do Spotify não está liberada. O app roda no Development Mode da Spotify (só contas convidadas) — use o demo ou o Last.fm.",
      session_expired: "Sua sessão terminou. Conecte o Spotify de novo ou explore o demo.",
      not_configured: "O login com Spotify ainda não está configurado neste ambiente — explore o demo.",
    },
    lastfmErrors: {
      lastfm_not_found: "Não encontramos esse usuário do Last.fm. Confira a grafia.",
      lastfm_private: "Este perfil do Last.fm é privado.",
      lastfm_unavailable: "O Last.fm não está respondendo agora. Tente de novo em instantes.",
      lastfm_not_configured: "O Last.fm ainda não está configurado neste ambiente.",
    },
  },
  lastfmForm: {
    eyebrow: "Sem convite",
    title: "Use seu Last.fm",
    description:
      "A Spotify só permite login de contas convidadas neste app. Se você registra o que ouve no Spotify no {link}, digite seu usuário para ver suas estatísticas — com gêneros das tags do Last.fm.",
    label: "Usuário do Last.fm",
    placeholder: "ex.: rj",
    submit: "Ver estatísticas",
    sectionLabel: "Usar Last.fm",
  },
  overview: {
    title: "Visão geral",
    description: "Seu resumo musical · {range}",
    highlightsLabel: "Destaques",
    topArtist: "Top artista",
    topTrack: "Top música",
    topGenre: "Top gênero",
    topEra: "Top época",
    recentlyPlayed: "Tocada recentemente",
    noData: "Sem dados ainda",
    nothingYet: "Nada ainda",
    unknown: "Desconhecida",
    followers: "{n} seguidores",
    inTopTracks: "Em {n} das suas top músicas",
    ofTopArtists: "{n} de {total} top artistas",
    ofTopTracks: "{n} das suas {total} top músicas",
    noReleaseDates: "Sem datas de lançamento",
    genreTitle: "Distribuição de gêneros",
    genreDescription: "Com base em {source} dos seus {n} top artistas — não em todo o seu histórico.",
    genreSourceFallback: "os gêneros",
    genreSources: { lastfm: "as tags do Last.fm", spotify: "os gêneros da Spotify" },
    decadeTitle: "Sua música por década",
    decadeDescription: "Ano de lançamento das suas {n} top músicas.",
    artistsTitle: "Artistas nas suas top músicas",
    artistsDescription: "Em quantas das suas {n} top músicas cada artista aparece.",
    tracksLabel: "Músicas",
    emptyTitle: "Sem top músicas ainda",
    emptyDescription: "Ouça mais músicas e volte depois — ou tente um período maior.",
    justNow: "agora",
    minutesAgo: "há {n} min",
    hoursAgo: "há {n} h",
    daysAgo: "há {n} d",
  },
  profile: {
    title: "Seu perfil musical",
    artistsAnalyzed: "Artistas analisados",
    tracksAnalyzed: "Músicas analisadas",
    topArtist: "Top artista",
    topTrack: "Top música",
    topGenre: "Gênero mais comum",
    genresDiscovered: "Gêneros descobertos",
    favouriteEra: "Época favorita",
    newestRelease: "Lançamento mais novo",
    oldestRelease: "Lançamento mais antigo",
    explicitTracks: "Músicas explícitas",
    averageLength: "Duração média",
  },
  nowPlaying: {
    label: "Tocando agora",
    paused: "Pausado",
    nothing: "Nada tocando agora",
    hint: "Dê play em algo e aparece aqui.",
    progress: "Progresso da música",
  },
  artists: {
    title: "Top artistas",
    description: "{n} artistas · {range}",
    top3: "Top 3 artistas",
    more: "Mais top artistas",
    plays: { one: "{n} play", other: "{n} plays" },
    followers: "{n} seguidores",
    popularity: "Popularidade {n}",
    emptyTitle: "Sem top artistas ainda",
    emptyDescription: "Não há histórico suficiente para este período. Tente um período maior.",
    popularityTitle: "Popularidade dos artistas",
    popularityDescription: "Índice de popularidade da Spotify (0–100) dos seus 10 top artistas.",
    popularityLabel: "Popularidade",
  },
  tracks: {
    title: "Top músicas",
    description: "{n} músicas · {range}",
    cover: "Capa",
    track: "Música",
    artist: "Artista",
    album: "Álbum",
    plays: "Plays",
    popularity: "Popularidade",
    duration: "Duração",
    playsCount: { one: "{n} play", other: "{n} plays" },
    coverAlt: "Capa de {name}",
    emptyTitle: "Sem top músicas ainda",
    emptyDescription: "Não há histórico suficiente para este período. Tente um período maior.",
  },
  recent: {
    title: "Tocadas recentemente",
    descriptionSpotify: "Suas últimas 50 músicas — o máximo que a API da Spotify oferece.",
    descriptionLastfm: "Seus últimos 50 scrobbles no Last.fm.",
    today: "Hoje",
    yesterday: "Ontem",
    emptyTitle: "Sem histórico ainda",
    emptyDescription: "Ouça algumas músicas e elas aparecem aqui.",
  },
  charts: {
    artistsCount: { one: "{n} artista", other: "{n} artistas" },
    tracksCount: { one: "{n} música", other: "{n} músicas" },
  },
  errors: {
    unauthorized: { title: "Sua sessão expirou", description: "Conecte sua conta do Spotify de novo para continuar explorando." },
    forbidden: {
      title: "Acesso negado",
      description: "Este app roda no Development Mode da Spotify, então só contas convidadas conseguem conectar. Experimente o demo.",
    },
    rate_limited: { title: "Muitas requisições", description: "O serviço está limitando as requisições agora. Espere alguns segundos e tente de novo." },
    unavailable: { title: "Serviço indisponível", description: "A API de música não está respondendo no momento. Tente novamente em instantes." },
    timeout: { title: "A requisição demorou demais", description: "O tempo esgotou. Confira sua conexão e tente de novo." },
    network: { title: "Problema de conexão", description: "Não conseguimos falar com a API de música. Confira sua conexão e tente de novo." },
    not_found: { title: "Usuário não encontrado", description: "Não encontramos esse usuário do Last.fm. Confira o nome e tente de novo." },
    unknown: { title: "Algo deu errado", description: "Aconteceu um erro inesperado ao carregar suas estatísticas. Tente novamente." },
    reconnect: "Reconectar Spotify",
    viewDemo: "Ver demo",
    tryAgain: "Tentar novamente",
    boundaryTitle: "Algo deu errado",
    boundaryDescription: "Não conseguimos carregar esta página. Tente novamente em instantes.",
  },
};
